
namespace TPO.UI
{
    using System;
    using System.Collections;
    using System.ComponentModel;
    using System.Data;
    using System.Diagnostics;
    using System.Drawing;
    using System.IO;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Windows.Forms;
    using TPO.Common;
    using TPO.Media;
    using TPO.Quiz;
    using TPO.TPOFile;
    using TPO.Utility;
    using System.Data.Common;
    using System.Data.SQLite;
    using System.Resources;
    using System.Reflection;

	public partial class MainForm : TestBaseForm
	{
        #region default UI interface
        private ImageList bgimagelist;
        private Button bn_readText;
        private Button btn_Answer01;
        private Button btn_Answer02;
        private Button btn_Answer03;
        private Button btn_Answer04;
        private Button btn_Answer05;
        private Button btn_Answer06;
        private Button btn_Answer07;
        private Button btn_Answer08;
        private Button btn_Answer09;
        private Button btn_Answer10;
        private Button btn_LastPage;
        private Button btn_LoadListening01;
        private Button btn_LoadListening02;
        private Button btn_LoadListening03;
        private Button btn_LoadListening04;
        private Button btn_LoadListening05;
        private Button btn_LoadListening06;
        private Button btn_LoadListening07;
        private Button btn_LoadListening08;
        private Button btn_LoadListening09;
        private Button btn_LoadListening10;
        private Button btn_LoadReading01;
        private Button btn_LoadReading02;
        private Button btn_LoadReading03;
        private Button btn_LoadReading04;
        private Button btn_LoadReading05;
        private Button btn_LoadReading06;
        private Button btn_LoadReading07;
        private Button btn_LoadReading08;
        private Button btn_LoadReading09;
        private Button btn_LoadReading10;
        private Button btn_LoadSpeaking01;
        private Button btn_LoadSpeaking02;
        private Button btn_LoadSpeaking03;
        private Button btn_LoadSpeaking04;
        private Button btn_LoadSpeaking05;
        private Button btn_LoadSpeaking06;
        private Button btn_LoadSpeaking07;
        private Button btn_LoadSpeaking08;
        private Button btn_LoadSpeaking09;
        private Button btn_LoadSpeaking10;
        private Button btn_LoadWriting01;
        private Button btn_LoadWriting02;
        private Button btn_LoadWriting03;
        private Button btn_LoadWriting04;
        private Button btn_LoadWriting05;
        private Button btn_LoadWriting06;
        private Button btn_LoadWriting07;
        private Button btn_LoadWriting08;
        private Button btn_LoadWriting09;
        private Button btn_LoadWriting10;
        private Button btn_NexPage;
        private Button btn_pause;
        private Button btn_QUITapp;
        private Button btn_Review01;
        private Button btn_Review02;
        private Button btn_Review03;
        private Button btn_Review04;
        private Button btn_Review05;
        private Button btn_Review06;
        private Button btn_Review07;
        private Button btn_Review08;
        private Button btn_Review09;
        private Button btn_Review10;
        private Button btn_showexplanation;
        private Button btn_ShowText;
        private Button btn_showtranslation;
        private Button btn_speakinganswer1;
        private Button btn_speakinganswer2;
        private Button btn_speakinganswer3;
        private Button btn_speakinganswer4;
        private Button btn_speakinganswer5;
        private Button btn_speakinganswer6;
        private Button btn_stopReading;
        private Button[] BtnLoadTest;
        private CheckBox ckb_A;
        private CheckBox ckb_B;
        private CheckBox ckb_C;
        private CheckBox ckb_D;
        private CheckBox ckb_E;
        private CheckBox ckb_F;
        private CheckBox ckb_G;
        private CheckBox ckb_H;
        private CheckBox ckb_ShowAnswer;
        private CheckBox ckb_sumAnswer1;
        private CheckBox ckb_sumAnswer10;
        private CheckBox ckb_sumAnswer2;
        private CheckBox ckb_sumAnswer3;
        private CheckBox ckb_sumAnswer4;
        private CheckBox ckb_sumAnswer5;
        private CheckBox ckb_sumAnswer6;
        private CheckBox ckb_sumAnswer7;
        private CheckBox ckb_sumAnswer8;
        private CheckBox ckb_sumAnswer9;
        private CheckBox ckb_SumSelected1;
        private CheckBox ckb_SumSelected2;
        private CheckBox ckb_SumSelected3;
        private CheckBox ckb_SumSelected4;
        private CheckBox ckb_SumSelected5;
        private CheckBox ckb_viewSpeakingText;
        private CheckBox[] CkbReading;
        private CheckBox[] CkbSummary;
        private CheckBox[] CkbSummarySelected;
        private IContainer components;
        private bool CONTINUECLICKED;
        private static int COVERFORM = 0;
        private int CurrentReadingPassage;
        private int CurrentReadingStep;
        private int CurrentSpeakingStep;
        private int CurrentTPOPage;
        private int CurrentWritingStep;
        private DataGridView dgv_listeninganswers;
        private DataGridView dgv_readinganswers;
        private DataGridView dgv_readingReview;
        private ExplanationUI EXP;
        public static string EXPLANATION = "";
        private Timer flash_timer;
        private FlowLayoutPanel flowLayoutPanel1;
        private FlowLayoutPanel flowLayoutPanel2;
        private FlowLayoutPanel flp_passage;
        public bool HasClickedNext;
        private bool HasLoadMP3;
        private int IBTScore;
        private string InsertSetenceRtf;
        public static bool ISACTIVED = false;
        private bool IsPassageMP3;
        public bool IsPause;
        private bool IsQuestionAfter;
        private bool IsRepeated;
        private SplitContainer l_splitContainer;
        private Label label1;
        private Label label10;
        private Label label11;
        private Label label12;
        private Label label13;
        private Label label14;
        private Label label15;
        private Label label16;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label7;
        private Label label8;
        private Label label9;
        private Label lbl_listeningScorereport;
        private Label lbl_readingIndication;
        private Label lbl_readingscorereport;
        private Label lbl_rightAnswered;
        private Label lbl_scoreReport;
        private Label lbl_tableAnswer;
        private Label lbl_testingSection;
        private Label lbl_top1;
        private Label lbl_top10;
        private Label lbl_top2;
        private Label lbl_top3;
        private Label lbl_top4;
        private Label lbl_top5;
        private Label lbl_top6;
        private Label lbl_top7;
        private Label lbl_top8;
        private Label lbl_top9;
        private Label lbl_writeDirection;
        private Label lbl_wrongAnswered;
        private CheckBox lckb_A;
        private CheckBox lckb_B;
        private CheckBox lckb_C;
        private CheckBox lckb_D;
        private CheckBox lckb_E;
        private CheckBox lckb_F;
        private CheckBox lckb_G;
        private CheckBox lckb_H;
        private CheckBox[] LCkbAnswers;
        private CheckBox[][] LCkbTable;
        private CheckBox lckbTable11;
        private CheckBox lckbTable12;
        private CheckBox lckbTable13;
        private CheckBox lckbTable14;
        private CheckBox lckbTable15;
        private CheckBox lckbTable21;
        private CheckBox lckbTable22;
        private CheckBox lckbTable23;
        private CheckBox lckbTable24;
        private CheckBox lckbTable25;
        private CheckBox lckbTable31;
        private CheckBox lckbTable32;
        private CheckBox lckbTable33;
        private CheckBox lckbTable34;
        private CheckBox lckbTable35;
        private CheckBox lckbTable41;
        private CheckBox lckbTable42;
        private CheckBox lckbTable43;
        private CheckBox lckbTable44;
        private CheckBox lckbTable45;
        private CheckBox lckbTable51;
        private CheckBox lckbTable52;
        private CheckBox lckbTable53;
        private CheckBox lckbTable54;
        private CheckBox lckbTable55;
        private CheckBox lckbTable61;
        private CheckBox lckbTable62;
        private CheckBox lckbTable63;
        private CheckBox lckbTable64;
        private CheckBox lckbTable65;
        private CheckBox lckbTable71;
        private CheckBox lckbTable72;
        private CheckBox lckbTable73;
        private CheckBox lckbTable74;
        private CheckBox lckbTable75;
        private CheckBox lckbTable81;
        private CheckBox lckbTable82;
        private CheckBox lckbTable83;
        private CheckBox lckbTable84;
        private CheckBox lckbTable85;
        private CheckBox lckbTable91;
        private CheckBox lckbTable92;
        private CheckBox lckbTable93;
        private CheckBox lckbTable94;
        private CheckBox lckbTable95;
        private static int LDIRECTION1 = 0;
        private static int LDIRECTION2 = 1;
        private static int LISTENING = 2;
        private Label llbl_rightAnswer;
        private TPOPassage LMaterial;
        private static int LMATERIALS = 2;
        private TabPage lMaterials1;
        private static int LMATERIALS1 = 3;
        private LinkLabel lnk_passage;
        public bool LOADLASTQUESTION;
        private static int LQUESTIONS = 4;
        private RichTextBox lrtb_answerA;
        private RichTextBox lrtb_answerB;
        private RichTextBox lrtb_answerC;
        private RichTextBox lrtb_answerD;
        private RichTextBox lrtb_answerE;
        private RichTextBox lrtb_answerF;
        private RichTextBox lrtb_answerG;
        private RichTextBox lrtb_answerH;
        private RichTextBox lrtb_question;
        private RichTextBox[] LRtbAnswers;
        private RichTextBox[] LRtbTableCol;
        private RichTextBox lrtbTableCol1;
        private RichTextBox lrtbTableCol2;
        private RichTextBox lrtbTableCol3;
        private RichTextBox lrtbTableCol4;
        private RichTextBox lrtbTableCol5;
        private RichTextBox lrtbTableQuestion;
        private RichTextBox[] LRtbTableRow;
        private RichTextBox lrtbTableRow1;
        private RichTextBox lrtbTableRow2;
        private RichTextBox lrtbTableRow3;
        private RichTextBox lrtbTableRow4;
        private RichTextBox lrtbTableRow5;
        private RichTextBox lrtbTableRow6;
        private RichTextBox lrtbTableRow7;
        private RichTextBox lrtbTableRow8;
        private RichTextBox lrtbTableRow9;
        private TabPage ltab_Direction1;
        private TabPage ltab_Direction2;
        private TabPage ltab_Materials;
        private TabPage ltab_Question;
        private TabPage lTableQuestion;
        private static int LTABLEQUESTION = 5;
        private TableLayoutPanel ltlp_table;
        private MP3MCI MP3Player;
        private MP3Record MP3Recorder;
        private int NotAnsweredQuestions;
        private OpenFileDialog openMp3File;
        private Panel panel1;
        private int PartCount;
        private int PartLastPassageIndex;
        private int PartNO;
        private int PassageCount;
        private int PassageLastQuestionIndex;
        private int PassageNO;
        private ProgressBar pb_currentpos;
        private ProgressBar pb_currentpos1;
        private PictureBox pb_ListenScene;
        private PictureBox pb_ListenScene1;
        private PictureBox pb_rightAnswered;
        private PictureBox pb_speakingScene;
        private PictureBox pb_writingScene;
        private PictureBox pb_wrongAnswered;
        private PictureBox pictureBox1;
        private PictureBox pictureBox10;
        private PictureBox pictureBox11;
        private PictureBox pictureBox2;
        private PictureBox pictureBox3;
        private PictureBox pictureBox4;
        private PictureBox pictureBox5;
        private PictureBox pictureBox6;
        private PictureBox pictureBox7;
        private PictureBox pictureBox8;
        private PictureBox pictureBox9;
        private Label PlayFileName;
        private int PreFormHeight;
        private int PreFormWidth;
        private int PreInsertPosition;
        private int QuestionCount;
        private int QuestionNO;
        private RadioButton rb_PracticeMode;
        private RadioButton rb_TestMode;
        private static int RDIRECTION = 0;
        private static int READING = 1;
        private int ReadingPassageNo;
        private int ReviewSelectedQuestionNO;
        private int RightAnsweredQuestions;
        private TPOPassage RMaterial;
        private static int RNORMALQUESTION = 1;
        private static int RREVIEW = 3;
        private int RSpiltQuestionNO;
        private static int RSUMMARYQUESTION = 2;
        private TabPage rtab_Direction;
        private TabPage rtab_NormalQuestion;
        private TabPage rtab_Review;
        private TabPage rtab_SumQuestion;
        private RichTextBox rtb_answerA;
        private RichTextBox rtb_answerB;
        private RichTextBox rtb_answerC;
        private RichTextBox rtb_answerD;
        private RichTextBox rtb_answerE;
        private RichTextBox rtb_answerF;
        private RichTextBox rtb_answerG;
        private RichTextBox rtb_answerH;
        private RichTextBox rtb_Passage;
        private RichTextBox rtb_question;
        private RichTextBox rtb_sumAnswer1;
        private RichTextBox rtb_sumAnswer10;
        private RichTextBox rtb_sumAnswer2;
        private RichTextBox rtb_sumAnswer3;
        private RichTextBox rtb_sumAnswer4;
        private RichTextBox rtb_sumAnswer5;
        private RichTextBox rtb_sumAnswer6;
        private RichTextBox rtb_sumAnswer7;
        private RichTextBox rtb_sumAnswer8;
        private RichTextBox rtb_sumAnswer9;
        private RichTextBox rtb_sumPassage;
        private RichTextBox rtb_sumQuestion;
        private RichTextBox rtb_SumSelected1;
        private RichTextBox rtb_SumSelected2;
        private RichTextBox rtb_SumSelected3;
        private RichTextBox rtb_SumSelected4;
        private RichTextBox rtb_SumSelected5;
        private RadioButton rtb_writing1;
        private RadioButton rtb_writing2;
        private RichTextBox rtb_writinganswers;
        private RichTextBox RtbPreviousSelected;
        private RichTextBox[] RtbReadingAnswers;
        private RichTextBox[] RtbSumAnswersToBeSelected;
        private RichTextBox[] RtbSumSelected;
        private TabPage sDirection;
        private static int SDIRECTION = 0;
        private bool ShowPassage;
        private TabPage sNormalQuestions;
        private ProgressBar spb;
        private static int SPEAKING = 3;
        private string[] SpeakingQuestions;
        private string[] SPicturePaths;
        private string[] SPictureTimeLines;
        private static int SQUESTION = 1;
        private string[] SReadingMaterials;
        private RichTextBox srtb_introduction;
        private Label srtb_timeindicator;
        private Label srtb_timer;
        private int SummarySelectedAnswerIndex;
        private int[] SummarySelectedAnswers;
        private TabPage tab_CoverForm;
        private TabPage tab_Listening;
        private TabPage tab_listeninganswers;
        private TabPage tab_Reading;
        private TabPage tab_readinganswer;
        private TabPage tab_Speaking;
        private TabPage tab_speakinganswers;
        private TabPage tab_Writing;
        private TabPage tab_writinganswers;
        private TabControl tabf_answer;
        private TabControl tabf_Listening;
        private TabControl tabf_Reading;
        private TabControl tabf_speaking;
        private TabControl tabf_test;
        private TabControl tabf_tposelection;
        private TabControl tabf_writing;
        private TableLayoutPanel tableLayoutPanel1;
        private TableLayoutPanel tableLayoutPanel2;
        private TableLayoutPanel tableLayoutPanel3;
        private TabPage tabPage1;
        private TrackBar tb_currentpos;
        private TrackBar tb_currentpos1;
        private TrackBar tb_reading;
        private int TestMode;
        private TPOPart TestQuestions;
        private TestingSection TestSection;
        private DateTime TimeLimitation;
        private Timer Timer_Listening;
        private Timer Timer_reading;
        private Timer Timer_Speaking;
        private TableLayoutPanel tlp_answers;
        private TableLayoutPanel tlp_sumAnswers;
        private TableLayoutPanel tlp_Summary;
        private int TotalQuestions;
        private int TotalScore;
        private TabPage TPO10;
        private int TPONO;
        public static string TRANSLATION = "";
        private TranslationUI TRANSUI;
        private static int USERANSWERS = 5;
        public static string USERNAME = "";
        private Button wbtn_cut;
        private Button wbtn_paste;
        private Button wbtn_redo;
        private Button wbtn_undo;
        private Button wbtn_wordcount;
        private TabPage wDirection;
        private static int WDIRECTION = 0;
        private static int WINDEPENDENT = 3;
        private static int WINTERGRATED = 1;
        private Label wlbl_wordcount;
        private Panel wpanel;
        private ProgressBar wpb_speak;
        private TabPage wReading;
        private static int WRITING = 4;
        private string[] WritingQuestions;
        private int WrongAnsweredQuestions;
        private RichTextBox wrtb_reading;
        private RichTextBox wrtb_writing1;
        private RichTextBox wrtb_writing2;
        private RichTextBox wrtbQuestion2;
        private TabPage wSpeakingPassage;
        private static int WSPEECH = 2;
        private TrackBar wtb_speak;
        private BindingSource bindingSource_Section;
        private TabPage wWriting2;
        #endregion

        public MainForm()
        {
            int num;
            this.components = null;
            this.IsPassageMP3 = false;
            this.CurrentReadingStep = 0;
            this.PreFormHeight = 0x268;
            this.PreFormWidth = 0x31a;
            this.CurrentTPOPage = 1;
            this.TPONO = 0;
            this.PassageNO = 0;
            this.PartNO = 0;
            this.QuestionNO = 0;
            this.RSpiltQuestionNO = 0;
            this.ReviewSelectedQuestionNO = -1;
            this.TestMode = 0;
            this.PartCount = 0;
            this.PassageCount = 0;
            this.QuestionCount = 0;
            this.PassageLastQuestionIndex = 0;
            this.PartLastPassageIndex = 0;
            this.InsertSetenceRtf = "";
            this.PreInsertPosition = -1;
            this.MP3Player = new MP3MCI();
            this.IsRepeated = false;
            this.IsQuestionAfter = false;
            this.HasLoadMP3 = false;
            this.CurrentSpeakingStep = 0;
            this.CurrentWritingStep = 0;
            this.BtnLoadTest = new Button[0x3d];
            this.CkbReading = new CheckBox[8];
            this.RtbReadingAnswers = new RichTextBox[8];
            this.CkbSummary = new CheckBox[10];
            this.CkbSummarySelected = new CheckBox[5];
            this.RtbSumAnswersToBeSelected = new RichTextBox[10];
            this.RtbSumSelected = new RichTextBox[5];
            this.SummarySelectedAnswerIndex = -1;
            this.ShowPassage = false;
            this.SummarySelectedAnswers = new int[5];
            this.LCkbAnswers = new CheckBox[8];
            this.LRtbAnswers = new RichTextBox[8];
            this.LRtbTableRow = new RichTextBox[9];
            this.LRtbTableCol = new RichTextBox[5];
            this.LCkbTable = new CheckBox[9][];
            this.IsPause = false;
            this.LOADLASTQUESTION = false;
            this.HasClickedNext = false;
            this.ReadingPassageNo = 1;
            this.CONTINUECLICKED = false;
            this.TotalScore = 0;
            this.RightAnsweredQuestions = 0;
            this.WrongAnsweredQuestions = 0;
            this.NotAnsweredQuestions = 0;
            this.TotalQuestions = 0;
            this.IBTScore = 0;
            this.EXP = new ExplanationUI();
            this.TRANSUI = new TranslationUI();
            this.CurrentReadingPassage = 1;
            this.InitializeComponent();
            this.PreFormHeight = base.Height;
            this.PreFormWidth = base.Width;
            base.WindowState = FormWindowState.Maximized;
            this.CkbReading[0] = this.ckb_A;
            this.CkbReading[1] = this.ckb_B;
            this.CkbReading[2] = this.ckb_C;
            this.CkbReading[3] = this.ckb_D;
            this.CkbReading[4] = this.ckb_E;
            this.CkbReading[5] = this.ckb_F;
            this.CkbReading[6] = this.ckb_G;
            this.CkbReading[7] = this.ckb_H;
            this.LCkbAnswers[0] = this.lckb_A;
            this.LCkbAnswers[1] = this.lckb_B;
            this.LCkbAnswers[2] = this.lckb_C;
            this.LCkbAnswers[3] = this.lckb_D;
            this.LCkbAnswers[4] = this.lckb_E;
            this.LCkbAnswers[5] = this.lckb_F;
            this.LCkbAnswers[6] = this.lckb_G;
            this.LCkbAnswers[7] = this.lckb_H;
            this.RtbReadingAnswers[0] = this.rtb_answerA;
            this.RtbReadingAnswers[1] = this.rtb_answerB;
            this.RtbReadingAnswers[2] = this.rtb_answerC;
            this.RtbReadingAnswers[3] = this.rtb_answerD;
            this.RtbReadingAnswers[4] = this.rtb_answerE;
            this.RtbReadingAnswers[5] = this.rtb_answerF;
            this.RtbReadingAnswers[6] = this.rtb_answerG;
            this.RtbReadingAnswers[7] = this.rtb_answerH;
            this.LRtbAnswers[0] = this.lrtb_answerA;
            this.LRtbAnswers[1] = this.lrtb_answerB;
            this.LRtbAnswers[2] = this.lrtb_answerC;
            this.LRtbAnswers[3] = this.lrtb_answerD;
            this.LRtbAnswers[4] = this.lrtb_answerE;
            this.LRtbAnswers[5] = this.lrtb_answerF;
            this.LRtbAnswers[6] = this.lrtb_answerG;
            this.LRtbAnswers[7] = this.lrtb_answerH;
            for (num = 0; num < 9; num++)
            {
                this.LCkbTable[num] = new CheckBox[5];
                for (int i = 0; i < 5; i++)
                {
                    this.LCkbTable[num][i] = new CheckBox();
                }
            }
            this.LCkbTable[0][0] = this.lckbTable11;
            this.LCkbTable[0][1] = this.lckbTable12;
            this.LCkbTable[0][2] = this.lckbTable13;
            this.LCkbTable[0][3] = this.lckbTable14;
            this.LCkbTable[0][4] = this.lckbTable15;
            this.LCkbTable[1][0] = this.lckbTable21;
            this.LCkbTable[1][1] = this.lckbTable22;
            this.LCkbTable[1][2] = this.lckbTable23;
            this.LCkbTable[1][3] = this.lckbTable24;
            this.LCkbTable[1][4] = this.lckbTable25;
            this.LCkbTable[2][0] = this.lckbTable31;
            this.LCkbTable[2][1] = this.lckbTable32;
            this.LCkbTable[2][2] = this.lckbTable33;
            this.LCkbTable[2][3] = this.lckbTable34;
            this.LCkbTable[2][4] = this.lckbTable35;
            this.LCkbTable[3][0] = this.lckbTable41;
            this.LCkbTable[3][1] = this.lckbTable42;
            this.LCkbTable[3][2] = this.lckbTable43;
            this.LCkbTable[3][3] = this.lckbTable44;
            this.LCkbTable[3][4] = this.lckbTable45;
            this.LCkbTable[4][0] = this.lckbTable51;
            this.LCkbTable[4][1] = this.lckbTable52;
            this.LCkbTable[4][2] = this.lckbTable53;
            this.LCkbTable[4][3] = this.lckbTable54;
            this.LCkbTable[4][4] = this.lckbTable55;
            this.LCkbTable[5][0] = this.lckbTable61;
            this.LCkbTable[5][1] = this.lckbTable62;
            this.LCkbTable[5][2] = this.lckbTable63;
            this.LCkbTable[5][3] = this.lckbTable64;
            this.LCkbTable[5][4] = this.lckbTable65;
            this.LCkbTable[6][0] = this.lckbTable71;
            this.LCkbTable[6][1] = this.lckbTable72;
            this.LCkbTable[6][2] = this.lckbTable73;
            this.LCkbTable[6][3] = this.lckbTable74;
            this.LCkbTable[6][4] = this.lckbTable75;
            this.LCkbTable[7][0] = this.lckbTable81;
            this.LCkbTable[7][1] = this.lckbTable82;
            this.LCkbTable[7][2] = this.lckbTable83;
            this.LCkbTable[7][3] = this.lckbTable84;
            this.LCkbTable[7][4] = this.lckbTable85;
            this.LCkbTable[8][0] = this.lckbTable91;
            this.LCkbTable[8][1] = this.lckbTable92;
            this.LCkbTable[8][2] = this.lckbTable93;
            this.LCkbTable[8][3] = this.lckbTable94;
            this.LCkbTable[8][4] = this.lckbTable95;
            this.LRtbTableRow[0] = this.lrtbTableRow1;
            this.LRtbTableRow[1] = this.lrtbTableRow2;
            this.LRtbTableRow[2] = this.lrtbTableRow3;
            this.LRtbTableRow[3] = this.lrtbTableRow4;
            this.LRtbTableRow[4] = this.lrtbTableRow5;
            this.LRtbTableRow[5] = this.lrtbTableRow6;
            this.LRtbTableRow[6] = this.lrtbTableRow7;
            this.LRtbTableRow[7] = this.lrtbTableRow8;
            this.LRtbTableRow[8] = this.lrtbTableRow9;
            this.LRtbTableCol[0] = this.lrtbTableCol1;
            this.LRtbTableCol[1] = this.lrtbTableCol2;
            this.LRtbTableCol[2] = this.lrtbTableCol3;
            this.LRtbTableCol[3] = this.lrtbTableCol4;
            this.LRtbTableCol[4] = this.lrtbTableCol5;
            for (num = 0; num < 8; num++)
            {
                this.RtbReadingAnswers[num].TextChanged += new EventHandler(this.RtbAnswers_TextChanged);
                this.CkbReading[num].CheckedChanged += new EventHandler(this.Ckb_CheckedChanged);
                this.LCkbAnswers[num].CheckedChanged += new EventHandler(this.Ckb_CheckedChanged);
            }
            this.CkbSummary[0] = this.ckb_sumAnswer1;
            this.CkbSummary[1] = this.ckb_sumAnswer2;
            this.CkbSummary[2] = this.ckb_sumAnswer3;
            this.CkbSummary[3] = this.ckb_sumAnswer4;
            this.CkbSummary[4] = this.ckb_sumAnswer5;
            this.CkbSummary[5] = this.ckb_sumAnswer6;
            this.CkbSummary[6] = this.ckb_sumAnswer7;
            this.CkbSummary[7] = this.ckb_sumAnswer8;
            this.CkbSummary[8] = this.ckb_sumAnswer9;
            this.CkbSummary[9] = this.ckb_sumAnswer10;
            this.RtbSumAnswersToBeSelected[0] = this.rtb_sumAnswer1;
            this.RtbSumAnswersToBeSelected[1] = this.rtb_sumAnswer2;
            this.RtbSumAnswersToBeSelected[2] = this.rtb_sumAnswer3;
            this.RtbSumAnswersToBeSelected[3] = this.rtb_sumAnswer4;
            this.RtbSumAnswersToBeSelected[4] = this.rtb_sumAnswer5;
            this.RtbSumAnswersToBeSelected[5] = this.rtb_sumAnswer6;
            this.RtbSumAnswersToBeSelected[6] = this.rtb_sumAnswer7;
            this.RtbSumAnswersToBeSelected[7] = this.rtb_sumAnswer8;
            this.RtbSumAnswersToBeSelected[8] = this.rtb_sumAnswer9;
            this.RtbSumAnswersToBeSelected[9] = this.rtb_sumAnswer10;
            for (num = 0; num < 10; num++)
            {
                this.RtbSumAnswersToBeSelected[num].TextChanged += new EventHandler(this.RtbAnswers_TextChanged);
                this.CkbSummary[num].CheckedChanged += new EventHandler(this.CkbSummary_CheckedChanged);
            }
            this.CkbSummarySelected[0] = this.ckb_SumSelected1;
            this.CkbSummarySelected[1] = this.ckb_SumSelected2;
            this.CkbSummarySelected[2] = this.ckb_SumSelected3;
            this.CkbSummarySelected[3] = this.ckb_SumSelected4;
            this.CkbSummarySelected[4] = this.ckb_SumSelected5;
            this.RtbSumSelected[0] = this.rtb_SumSelected1;
            this.RtbSumSelected[1] = this.rtb_SumSelected2;
            this.RtbSumSelected[2] = this.rtb_SumSelected3;
            this.RtbSumSelected[3] = this.rtb_SumSelected4;
            this.RtbSumSelected[4] = this.rtb_SumSelected5;
            for (num = 0; num < 5; num++)
            {
                this.RtbSumSelected[num].Click += new EventHandler(this.RtbSumSelected_Click);
                this.RtbSumSelected[num].TextChanged += new EventHandler(this.RtbAnswers_TextChanged);
                this.CkbSummarySelected[num].CheckedChanged += new EventHandler(this.CkbSummarySelected_CheckedChanged);
            }
            this.rtb_question.TextChanged += new EventHandler(this.RtbAnswers_TextChanged);
            this.rtb_sumQuestion.TextChanged += new EventHandler(this.RtbAnswers_TextChanged);
            this.BtnLoadTest[1] = this.btn_LoadReading01;
            this.BtnLoadTest[2] = this.btn_LoadReading02;
            this.BtnLoadTest[3] = this.btn_LoadReading03;
            this.BtnLoadTest[4] = this.btn_LoadReading04;
            this.BtnLoadTest[5] = this.btn_LoadReading05;
            this.BtnLoadTest[6] = this.btn_LoadReading06;
            this.BtnLoadTest[7] = this.btn_LoadReading07;
            this.BtnLoadTest[8] = this.btn_LoadReading08;
            this.BtnLoadTest[9] = this.btn_LoadReading09;
            this.BtnLoadTest[10] = this.btn_LoadReading10;
            this.BtnLoadTest[11] = this.btn_LoadListening01;
            this.BtnLoadTest[12] = this.btn_LoadListening02;
            this.BtnLoadTest[13] = this.btn_LoadListening03;
            this.BtnLoadTest[14] = this.btn_LoadListening04;
            this.BtnLoadTest[15] = this.btn_LoadListening05;
            this.BtnLoadTest[0x10] = this.btn_LoadListening06;
            this.BtnLoadTest[0x11] = this.btn_LoadListening07;
            this.BtnLoadTest[0x12] = this.btn_LoadListening08;
            this.BtnLoadTest[0x13] = this.btn_LoadListening09;
            this.BtnLoadTest[20] = this.btn_LoadListening10;
            this.BtnLoadTest[0x15] = this.btn_LoadSpeaking01;
            this.BtnLoadTest[0x16] = this.btn_LoadSpeaking02;
            this.BtnLoadTest[0x17] = this.btn_LoadSpeaking03;
            this.BtnLoadTest[0x18] = this.btn_LoadSpeaking04;
            this.BtnLoadTest[0x19] = this.btn_LoadSpeaking05;
            this.BtnLoadTest[0x1a] = this.btn_LoadSpeaking06;
            this.BtnLoadTest[0x1b] = this.btn_LoadSpeaking07;
            this.BtnLoadTest[0x1c] = this.btn_LoadSpeaking08;
            this.BtnLoadTest[0x1d] = this.btn_LoadSpeaking09;
            this.BtnLoadTest[30] = this.btn_LoadSpeaking10;
            this.BtnLoadTest[0x1f] = this.btn_LoadWriting01;
            this.BtnLoadTest[0x20] = this.btn_LoadWriting02;
            this.BtnLoadTest[0x21] = this.btn_LoadWriting03;
            this.BtnLoadTest[0x22] = this.btn_LoadWriting04;
            this.BtnLoadTest[0x23] = this.btn_LoadWriting05;
            this.BtnLoadTest[0x24] = this.btn_LoadWriting06;
            this.BtnLoadTest[0x25] = this.btn_LoadWriting07;
            this.BtnLoadTest[0x26] = this.btn_LoadWriting08;
            this.BtnLoadTest[0x27] = this.btn_LoadWriting09;
            this.BtnLoadTest[40] = this.btn_LoadWriting10;
            this.BtnLoadTest[0x29] = this.btn_Review01;
            this.BtnLoadTest[0x2a] = this.btn_Review02;
            this.BtnLoadTest[0x2b] = this.btn_Review03;
            this.BtnLoadTest[0x2c] = this.btn_Review04;
            this.BtnLoadTest[0x2d] = this.btn_Review05;
            this.BtnLoadTest[0x2e] = this.btn_Review06;
            this.BtnLoadTest[0x2f] = this.btn_Review07;
            this.BtnLoadTest[0x30] = this.btn_Review08;
            this.BtnLoadTest[0x31] = this.btn_Review09;
            this.BtnLoadTest[50] = this.btn_Review10;
            this.BtnLoadTest[0x33] = this.btn_Answer01;
            this.BtnLoadTest[0x34] = this.btn_Answer02;
            this.BtnLoadTest[0x35] = this.btn_Answer03;
            this.BtnLoadTest[0x36] = this.btn_Answer04;
            this.BtnLoadTest[0x37] = this.btn_Answer05;
            this.BtnLoadTest[0x38] = this.btn_Answer06;
            this.BtnLoadTest[0x39] = this.btn_Answer07;
            this.BtnLoadTest[0x3a] = this.btn_Answer08;
            this.BtnLoadTest[0x3b] = this.btn_Answer09;
            this.BtnLoadTest[60] = this.btn_Answer10;
        }
	}
}
